# Site settings
title: Tara's Blog
header-img: img/home-bg.png
email: tarajmeyerink@gmail.com
copyright_name: tmeyerink
description: > # this means to ignore newlines until "baseurl:"
  Always learning, never taking a break
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tmeyerink
learn_profile: tmeyerink
email_username: tarajmeyerink@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
